[[files]]
source = "/home/thor/obsidian/writing/blog/Getting Started with Obsidian.md"
target = "/home/thor/projects/obsidian-setup/Getting Started with Obsidian.md"

[[files]]
source = "/home/thor/obsidian/writing/blog/Solving ZK Hack IV puzzle 2 - Supervillain.md"

[[files]]
source = "/home/thor/obsidian/writing/blog/Solving ZK Hack IV puzzle 1 - Gamma Ray.md"

[[files]]
source = "/home/thor/obsidian/writing/blog/about_me.md"
target = "/home/thor/projects/blog/content/about/_index.md"

[[files]]
source = "/home/thor/obsidian/writing/blog/git-merkle.md"

[[files]]
source = "/home/thor/obsidian/writing/blog/solving zk-hack puzzle 3 - Chaos Theory.md"
